theme: jekyll-theme-tactile
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - test_GeoInfo.md
  - test_GeoRegion.md
  - test_GeoManager.md
  - help_cocoa.md
  - help_tools.md
  - help_covid19.md
  - help_error.md
  - help_geo.md
  - help_display.md